name: Deploy to Server

on:
  push:
    tags:
      - 'v*'

jobs:
  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Get JAR file name
      id: get_jar
      run: |
        JAR_FILE=$(find backend/second-server/target -name "*.jar" -type f | head -n 1)
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR file: $JAR_FILE"

    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: ${{ steps.get_jar.outputs.jar_file }}

    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "${{ steps.get_jar.outputs.jar_file }}"
        target: "/home/deployer/campus-mall-app/"
        strip_components: 4

    - name: Stop existing application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          if pgrep -f "second-server.*\.jar"; then
            sudo pkill -f "second-server.*\.jar"
            echo "Waiting for application to stop..."
            sleep 10
          fi
          
          # Check if process is still running and kill it forcefully if needed
          if pgrep -f "second-server.*\.jar"; then
            sudo pkill -9 -f "second-server.*\.jar"
            sleep 5
          fi

    - name: Create necessary directories
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mkdir -p /home/deployer/campus-mall-app/logs
          chmod +x /home/deployer/campus-mall-app/*.jar

    - name: Start application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/deployer/campus-mall-app
          nohup java -jar -Dspring.profiles.active=prod $(basename "${{ steps.get_jar.outputs.jar_file }}") > logs/app.log 2>&1 &
          echo "Application started with PID $!"
          sleep 10

    - name: Health Check
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://${{ secrets.HOST }}:8080/actuator/health
        max-attempts: 10
        retry-delay: 30s
        retry-all: true

    - name: Notify Deployment Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: '✅ Backend deployment completed successfully to production'
        channel: '#deployments'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Deployment Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: '❌ Backend deployment failed to production'
        channel: '#deployments'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: production
    needs: backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist

    - name: Deploy frontend to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "frontend/dist/*"
        target: "/home/deployer/campus-mall-frontend/"