name: Frontend CI/CD

on:
  push:
    branches: [ "master", "main" ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    tags:        
      - 'v*'
  pull_request:
    branches: [ "master", "main" ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  release:
    types: [published]

jobs:
  test:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install and build frontend
      run: |
        npm install
        npm run build
        if [ -f "package.json" ] && grep -q "test:unit" package.json; then
          npm run test:unit
        else
          echo "No test script found, skipping tests"
        fi
      working-directory: frontend
      continue-on-error: true

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: production
    needs: test
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'release' && github.event.action == 'published')

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Build and upload frontend
      run: |
        npm install
        npm run build
      working-directory: frontend

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist

    - name: Deploy frontend to temp directory
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "frontend/dist/*"
        target: "/tmp/frontend_dist/"
        overwrite: true

    # This step now uses password authentication from the PASSWORD secret
    # Make sure PASSWORD is configured in the GitHub repository secrets
    - name: Move files to nginx directory
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          # Ensure the script runs with proper error handling
          set -e
          
          # Use password authentication for all sudo commands
          echo "${{ secrets.PASSWORD }}" | sudo -S mkdir -p /var/www/html/
          echo "${{ secrets.PASSWORD }}" | sudo -S rm -rf /var/www/html/*
          echo "${{ secrets.PASSWORD }}" | sudo -S cp -r /tmp/frontend_dist/frontend/dist/* /var/www/html/
          echo "${{ secrets.PASSWORD }}" | sudo -S chown -R www-data:www-data /var/www/html/
          echo "${{ secrets.PASSWORD }}" | sudo -S chmod -R 755 /var/www/html/
          
          echo "Files moved to nginx directory successfully"