name: Frontend CI/CD

on:
  push:
    branches: [ "master", "main" ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "master", "main" ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  release:
    types: [published]

jobs:
  test:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Run frontend tests
      run: |
        if [ -f "frontend/package.json" ] && grep -q "test:unit" frontend/package.json; then
          npm run test:unit
        else
          echo "No test script found, skipping tests"
        fi
      working-directory: frontend
      continue-on-error: true

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: production
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist

    - name: Deploy frontend to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "frontend/dist/*"
        target: "/home/deployer/campus-mall-frontend/"